services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: memory-mcp-postgres
    environment:
      POSTGRES_DB: memory_mcp
      POSTGRES_USER: memory_user
      POSTGRES_PASSWORD: memory_password
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
